Module 2 Zakupka Prodaja Proizvodstvo/Module 2 Zakupka Prodaja Proizvodstvo/Models/Ingredient.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public byte ingr_ID { get; set; }
        public Nullable<byte> produciya { get; set; }
        public Nullable<short> syrie { get; set; }
        public Nullable<double> kol_vo { get; set; }
    
        public virtual Gotov_product Gotov_product { get; set; }
        public virtual Syrie Syrie1 { get; set; }
    }
}

Module 2 Zakupka Prodaja Proizvodstvo/Module 2 Zakupka Prodaja Proizvodstvo/Controllers/IngredientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using Module_2_Zakupka_Prodaja_Proizvodstvo.Models;
namespace Module_2_Zakupka_Prodaja_Proizvodstvo.Controllers
{
    public class IngredientController : Controller
    {
        ProdajProductContext db = new ProdajProductContext();
        // GET: Ingredient
        public ActionResult Index(int? product,int? syrie)
        {
            bool da = true;
            IQueryable<Ingredient> proizvodstvos = db.Ingredients.Include(p => p.Syrie1);
            IQueryable<Ingredient> products = db.Ingredients.Include(p => p.Gotov_product);
            if (product != null && product != 0)
            {
                products = products.Where(p => p.produciya == product);
                da = false;
            }
            if (syrie != null && syrie != 0)
            {
                proizvodstvos = proizvodstvos.Where(p => p.syrie == syrie);
                da = true;
            }

            List<Syrie> syries = db.Syries.ToList();
            List<Gotov_product> gp_products = db.Gotov_Products.ToList();
            // устанавливаем начальный элемент, который позволит выбрать всех
            syries.Insert(0, new Syrie { name = "Все", syrie_id = 0 });
            gp_products.Insert(0, new Gotov_product { name = "Все", gp_ID = 0 });
            if (da == true)
            {
                IngredientVM plvm = new IngredientVM
                {
                   Ingredientsi = proizvodstvos.ToList(),
                    Syriesi = new SelectList(syries, "syrie_id", "name"),
                    Productsi = new SelectList(gp_products, "gp_ID", "name"),
                };


                return View(plvm);
            }
            else
            {
                IngredientVM plvm = new IngredientVM
                {
                   Ingredientsi = products.ToList(),
                    Syriesi = new SelectList(syries, "syrie_id", "name"),
                    Productsi = new SelectList(gp_products, "gp_ID", "name"),
                };


                return View(plvm);
            }

        }

        [HttpGet]
        public ActionResult Index(int id)
        {
            ViewBag.Ingredients = db.Database.SqlQuery<Ingredient_Gotov_Result>("EXEC dbo.Ingredient_Gotov {0}", id);
            return View(ViewBag.Ingredients);
        }
        [HttpGet]
        public ActionResult Create()
        {
            // Формируем список команд для передачи в представление
            SelectList proizvodstvos = new SelectList(db.Gotov_Products, "gp_ID", "name");
            ViewBag.Gotov_Products = proizvodstvos;
            SelectList syries = new SelectList(db.Syries, "syrie_id", "name");
            ViewBag.Syries = syries;
            return View();
        }

        [HttpPost]
        public ActionResult Create(Ingredient ingredients)
        {
            //Добавляем игрока в таблицу
            db.Ingredients.Add(ingredients);
            db.SaveChanges();
            // перенаправляем на главную страницу
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }
            Ingredient ingredient = db.Ingredients.Find(id);
            if (ingredient != null)
            {
                return View(ingredient);
            }
            return HttpNotFound();
        }
        [HttpPost]
        public ActionResult Edit(Ingredient ingredient)
        {
            db.Entry(ingredient).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Module 2 Zakupka Prodaja Proizvodstvo/Module 2 Zakupka Prodaja Proizvodstvo/Views/Ingredient/Create.cshtml
@model Module_2_Zakupka_Prodaja_Proizvodstvo.Models.IngredientVM

@{
    ViewBag.Title = "Добавление";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Добавление</h2>

@using (Html.BeginForm())
{
    <fieldset>
        <legend>Ингредиент</legend>

        <p>
           Прдукт<br />
            @Html.DropDownListFor(model => model.produciya, ViewBag.Gotov_products as SelectList)
        </p>

        <p>
            Сырье<br />
            @Html.DropDownListFor(model => model.syrie, ViewBag.Syries as SelectList)
        </p>

        <p>
            Количество  <br />

            @Html.EditorFor(model => model.kol_vo)
        </p>

        <p>
            <input type="submit" value="Добавить" />
        </p>
    </fieldset>



}
<div>

    @Html.ActionLink("К списку", "Index")
</div>

Module 2 Zakupka Prodaja Proizvodstvo/Module 2 Zakupka Prodaja Proizvodstvo/Views/Ingredient/Edit.cshtml
@{
    ViewBag.Title = "Редактировать";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@model Module_2_Zakupka_Prodaja_Proizvodstvo.Models.IngredientVM
<h2>Ингредиент № @Model.ingr_ID</h2>
@using (Html.BeginForm("Edit", "Ingredient", FormMethod.Post))
{
    <fieldset>
        @Html.HiddenFor(m => m.ingr_ID)
        <p>
            @Html.LabelFor(m => m.produciya, "Продукт")
                     <br />
            @Html.DropDownListFor(m => m.produciya, ViewBag.Gotov_products as SelectList)
        </p>
        <p>
            @Html.LabelFor(m => m.syrie, "Cырье")
            <br />
            @Html.DropDownListFor(m => m.syrie, ViewBag.Syries as SelectList)
        </p>
        <p>
            @Html.LabelFor(m => m.kol_vo, "Количество")
            <br />
            @Html.EditorFor(m => m.kol_vo)
        </p>
        <p><input type="submit" value="Отправить" /></p>
    </fieldset>
}

Module 2 Zakupka Prodaja Proizvodstvo/Module 2 Zakupka Prodaja Proizvodstvo/Views/Ingredient/Index.cshtml
@model IEnumerable <Module_2_Zakupka_Prodaja_Proizvodstvo.Models.Ingredient_Gotov_Result>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
          Наименование продукта
        </th>
        <th>
        Количество сырья
        </th>
        <th>
            Необходимо сырья
        </th>
        <th></th>
    </tr>

@foreach (Module_2_Zakupka_Prodaja_Proizvodstvo.Models.Ingredient_Gotov_Result b in ViewBag.Ingredients) {
    <tr>
        <td>
            @b.Product
        </td>
        <td>
           @b.kol_vo
        </td>
        <td>
            @b.name
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=b.Product }) |
            @Html.ActionLink("Delete", "Delete", new { id=b.Product})
        </td>
    </tr>
}

</table>